# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Test Environment
        required: true
        options:
          - dev
          - stg
          - prd

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-workflow:
    uses: ./.github/workflows/_shared-template.yml
    with:
      env: ${{ inputs.env }}

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.env }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

  deploy:
    environment: ${{ inputs.env }} 
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
